### ISSUE TITLE
Filtering by the assignee's username

### ISSUE THREAD

**Issue by johnyoonh** [ogarcia/trellowarrior#17]
This project works great for a personal board, but when I tried to run sync on a collaborative board, it would import all projects regardless of the assignee. The owner's username should be used to filter them out.

**Comment by lukasredev** [comment]
This would be a great feature, @ogarcia would you accept a PR implementing this?

**Comment by ogarcia** [comment]
@lukasreichart yes, I think that can be a new config option by `sync_project`

**Comment by johnyoonh** [comment]
If https://github.com/ogarcia/trellowarrior/pull/15
is merged in, I will make a pull request of my commits.
https://github.com/johnyoonh/trellowarrior/commits/master

**Comment by ogarcia** [comment]
I have refactored the code and #15 cannot be applied, but I think that I can implement an `trello_card_members` to download only the cards that owns any of members defined in these option, and `trello_list_filter`, to define what lists you don't want to sinchronize.

**Comment by ogarcia** [comment]
Added `trello_lists_filter` :tada:

I need to think the user filter, not is easy since for now TrelloWarrior dont set the owner of Trello cards, and if you filter by user, you lose the tasks created in Taskwarrior after sync.

Maybe add a option like "only my tasks" and if enabled all tasks created in Taskwarrior will be uploaded to trello assigned to your user.
