### ISSUE TITLE
due date removed in Taskwarrior do not propagate

### ISSUE THREAD

**Issue by bcohen44** [ogarcia/trellowarrior#31]
1. I add a due date in Taskwarrior.  
2. Run trellowarrior sync, due date syncs to Trello.  
3. Remove due date in Taskwarrior
4. run trellowarrior sync, due date does not go away in Trello, and due date _returns_ to task in taskwarrior

**Comment by bcohen44** [comment]
And the bug exists going the other way, removing date from Trello first has no affect, due date sticks in both places.

**Comment by ogarcia** [comment]
@bcohen44 Sorry for the delay, too much work and too little time.

Yes, is a [known limitation](https://github.com/ogarcia/trellowarrior#known-limitations), which was missing in the README, I have added it now:
If you want to delete a due date you must do it in both Taskwarrior and Trello.

The main reason for this limitation is that since it is a completely optional item you have no way of knowing if the user has deleted it or if it has simply not been previously synchronized. So when the field does not exist on either side it is synchronized.

There is no way to fix the problem (hence it is a known limitation) without using status files, which is beyond the scope of this application (remember, the main objective is to be simple).
